export const NOTIFICATION_TYPES = {
    VACATION_REQUEST: 'VACATION_REQUEST',
    VACATION_RESPONSE: 'VACATION_RESPONSE',
    PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    PAYMENT_REFUNDED: 'PAYMENT_REFUNDED'
}; 